"""
將 components/ 下的元件依依賴順序合併成單一 dist/components-bundle.js。
這樣 index.html 只需引用一個 <script type="text/babel">，避免 Babel Standalone
平行載入導致執行順序錯亂、以及 file:// 直開時 fetch 被擋的問題。

用法：
    python scripts/bundle.py
"""

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPONENTS_DIR = ROOT / "components"
DIST_DIR = ROOT / "dist"
OUT_FILE = DIST_DIR / "components-bundle.js"

# 依依賴順序排列（上層被下層引用）
ORDER = [
    "Icons.js",
    "constants.js",
    "MetricComponents.js",
    "PlayTypeCard.js",
    "TrackingCardRow.js",
    "ShotChart.js",
    "DefenseHeatmap.js",
    "gameAggregates.js",
    "gamesData.js",
    "SingleGamePanel.js",
    "OverviewTab.js",
    "SplitsTab.js",
    "ShootingTab.js",
    "ComparisonTab.js",
    "RadarPanel.js",
    "App.js",
]


def main():
    DIST_DIR.mkdir(exist_ok=True)
    parts = ["// === auto-generated by scripts/bundle.py — DO NOT EDIT MANUALLY ===\n"]
    for name in ORDER:
        src = COMPONENTS_DIR / name
        if not src.exists():
            raise FileNotFoundError(f"找不到元件：{src}")
        parts.append(f"\n// ---------- {name} ----------\n")
        parts.append(src.read_text(encoding="utf-8"))
        parts.append("\n")
    OUT_FILE.write_text("".join(parts), encoding="utf-8")
    size_kb = OUT_FILE.stat().st_size / 1024
    print(f"[OK] 已產生 {OUT_FILE.relative_to(ROOT)}（{size_kb:.1f} KB，{len(ORDER)} 個元件）")


if __name__ == "__main__":
    main()
